name = "job-kanban-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"

# Cloudflare AI Gateway configuration
[vars]
CLOUDFLARE_GATEWAY_ID = "job-parser-getaway"
# CLOUDFLARE_ACCOUNT_ID should be set via wrangler secret put CLOUDFLARE_ACCOUNT_ID

# Production environment
[env.production]
vars = { ENVIRONMENT = "production" }
# Route will be set up via Custom Domain in Cloudflare dashboard
# or use default workers.dev subdomain

# Development environment
[env.development]
vars = { ENVIRONMENT = "development" }

# Required secrets configuration
# Set these using wrangler:
#   wrangler secret put SUPABASE_URL
#   wrangler secret put SUPABASE_SERVICE_KEY
#   wrangler secret put SUPABASE_JWT_SECRET  # JWT Secret from Supabase Project Settings > API
#   wrangler secret put ANTHROPIC_API_KEY
#   wrangler secret put JINA_API_KEY  # Optional: For better rate limits (200 RPM, 10M free tokens)
#   wrangler secret put CLOUDFLARE_ACCOUNT_ID  # Cloudflare account ID (previously hardcoded)

# Cron triggers for background job processing
[triggers]
crons = ["*/5 * * * *"]  # Run every 5 minutes

# Security best practices:
# 1. Use wrangler secret put for all sensitive values
# 2. CORS is configured in code (src/index.ts)
# 3. Restrict allowed origins in code
# 4. Regular secret rotation using wrangler
# 5. Monitor usage and set up alerts

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
