repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
        name: Detect hardcoded secrets
        description: Prevent secrets from being committed
        entry: gitleaks protect --verbose --redact

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: detect-private-key
        name: Detect private keys
      - id: detect-aws-credentials
        name: Detect AWS credentials
      - id: detect-env-secrets
        name: Detect .env secrets